# Generated by Django 5.1.6 on 2025-02-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
